# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    
jobs:

  build: 
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull marlonrodris/node-simple-backend-application:latest
      
      - name: Delete Old docker container
        run: sudo docker rm -f backendapp-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 5000:5000 --name backendapp-container marlonrodris/node-simple-backend-application

