# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    
jobs:
  runs-on: self-hosted

  steps:
    - name: Stop container
      run: sudo docker compose stop
    
    - name: Remove container
      run: sudo docker compose down

    - name: Remove Image
      run: sudo docker rmi marlonrodris/node-simple-backend-application

    - name: Create new container
      run: sudo docker compose up

