# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop"]    

jobs:
  test-cli:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

  deploy-test:
    needs: test-cli 
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    concurrency: deploy-to-test
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Build and push the Docker image
        run: docker build -t new-tested-app-image .

      - name: "Feedback of the test"
        run: echo "Build Complete"    

  deploy-production:
    needs: test-cli
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t marlonrodris/node-simple-backend-application:1.0.0 .

      - name: Tag Docker image 
        run: docker tag marlonrodris/node-simple-backend-application:1.0.0 marlonrodris/node-simple-backend-application:latest
      
      - name: Push the Docker image
        run: docker tag marlonrodris/node-simple-backend-application:1.0.0 

      - name: Push the latest version of the Docker image to Docker Hub
        run: docker push marlonrodris/node-simple-backend-application:latest
